### ISSUE TITLE
Landing page links are broken

### ISSUE THREAD

**Issue by mrhoodz** [genie-design/qwikbits#1]
**Describe the bug**
The links on the Landing page are broken

**To Reproduce**
1. Go to 'landing page'
2. Click on 'any link'
3. See error

**Expected behavior**
The links dont navigate to the destination urls.

**Comment by acoreyj** [comment]
@mrhoodz thanks it seems Chrome shipped native popover and their implementation didn't work with my Dropdown element causing a JS error.

Should be fixed now can you re-test

**Comment by mrhoodz** [comment]
Website seems to be working fine now
